# Generated by Django 4.2 on 2023-05-01 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tanks', 'Tanks'), ('Heals', 'Heals'), ('Damage Dealers', 'Damage Dealers'), ('Traders', 'Traders'), ('Gild masters', 'Gild Masters'), ('Quest givers', 'Quest givers'), ('Blacksmiths', 'Blaksmiths'), ('Tanners', 'Tanners'), ('Potion masters', 'Potion masters'), ('Spell masters', 'Spell masters')], default='Tanks', max_length=28)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField()),
                ('upload', models.FileField(upload_to='uploads/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('comment_accepted', models.BooleanField(default=False)),
                ('author_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
