# Generated by Django 4.2 on 2023-05-03 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_post_comment_comment_post_remove_post_upload_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='authorUser',
            new_name='author',
        ),
    ]
