# Generated by Django 4.1.9 on 2023-05-04 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_authoruser_author_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Tanks'), ('Heals', 'Heals'), ('Damage Dealers', 'Damage Dealers'), ('Traders', 'Traders'), ('Gild masters', 'Gild Masters'), ('Quest givers', 'Quest givers'), ('Blacksmiths', 'Blaksmiths'), ('Tanners', 'Tanners'), ('Potion masters', 'Potion masters'), ('Spell masters', 'Spell masters')], default='Tanks', max_length=28, verbose_name='category'),
        ),
    ]
