# Generated by Django 4.1.9 on 2023-05-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dateCreation',
            new_name='comment_dateCreation',
        ),
    ]
