# Generated by Django 4.1.9 on 2023-05-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rejected',
            field=models.BooleanField(default=True),
        ),
    ]
