# Generated by Django 4.1.9 on 2023-05-08 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_comment_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rejected',
        ),
    ]
