# Generated by Django 4.1.9 on 2023-05-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
