# Generated by Django 4.1.9 on 2023-05-09 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0016_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Tanks', 'Tanks'), ('Heals', 'Heals'), ('Damage Dealers', 'Damage Dealers'), ('Traders', 'Traders'), ('Gild masters', 'Gild Masters'), ('Quest givers', 'Quest givers'), ('Blacksmiths', 'Blacksmiths'), ('Tanners', 'Tanners'), ('Potion masters', 'Potion masters'), ('Spell masters', 'Spell masters')], default='Tanks', max_length=28, verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
