# Generated by Django 4.1.9 on 2023-05-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
