# Generated by Django 4.1.9 on 2023-05-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_comment_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='seen',
            new_name='rejected',
        ),
    ]
