# Generated by Django 4.1.9 on 2023-05-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_rename_seen_comment_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rejected',
        ),
    ]
